apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      name: analysis
      labels:
        app: analysis
    spec:
      containers:
        - name: analysis
          image: analysis
          imagePullPolicy: IfNotPresent